from __future__ import annotations

import discord

from rob.ui.render import RenderedMessage, require_components_v2
from rob.ui.theme import COLOR_ROB_PURPLE

PRIVACY_NOTICE_FOOTER = "-# Privacy Notice valid as of 25/05/2026"


def _privacy_container(*, title: str, body: str) -> discord.ui.Container:
    return discord.ui.Container(
        discord.ui.TextDisplay(title),
        discord.ui.Separator(),
        discord.ui.TextDisplay(body),
        discord.ui.TextDisplay(PRIVACY_NOTICE_FOOTER),
        accent_color=COLOR_ROB_PURPLE,
    )


def privacy_notice_message() -> RenderedMessage:
    require_components_v2()
    view = discord.ui.LayoutView(timeout=1800)

    view.add_item(
        _privacy_container(
            title="## Rob Privacy Notice",
            body=(
                "This notice describes the categories of information that Rob may receive, store, and process when users interact with its features.\n\n"
                "It also explains the purposes for which that information is used, the circumstances in which information may be displayed within the server, and the options available to users who wish to request removal of information associated with them."
            ),
        )
    )

    view.add_item(
        _privacy_container(
            title="## Information Collected or Received",
            body=(
                "Rob is designed to collect and store only the information reasonably required to provide its configured features.\n\n"
                "The categories of information received or stored may vary depending on the features a user registers for, enables, or interacts with.\n\n"
                "**__General Bot Operation__**\n\n"
                "-# - Discord User ID\n"
                "-# - Discord username, global display name, server nickname, or display name where required\n"
                "-# - Discord server ID\n"
                "-# - Discord channel IDs required for configured bot features\n"
                "-# - Discord role IDs required for permission checks and feature access\n"
                "-# - Command interaction data required to process and respond to user requests\n\n"
                "**__Registration Features__**\n\n"
                "-# - Discord User ID\n"
                "-# - Discord server ID\n"
                "-# - Registered Dom/me or Sub status\n"
                "-# - Registered Sub send name, where provided\n"
                "-# - Throne handle or Throne profile URL, where provided for Throne tracking\n"
                "-# - Registration timestamps\n\n"
                "**__Automatic Throne Tracking__**\n\n"
                "**Information received from Throne may include:**\n\n"
                "-# - Creator ID, which is an identifier generated by Throne for the creator account\n"
                "-# - Throne username\n"
                "-# - Gifter username\n"
                "-# - Gift message, where provided by Throne\n"
                "-# - Item name\n"
                "-# - Item image URL\n"
                "-# - Item price\n"
                "-# - Currency\n"
                "-# - Whether the item is marked as a surprise gift, although Rob does not currently use this field\n\n"
                "**Additional collection by Rob:**\n\n"
                "-# As of the Rob rebuild in June 2026, Rob no longer actively collects information from public Throne wishlists. If future functionality requires additional Throne-related information, this notice should be updated before or at the time that functionality is introduced.\n\n"
                "**__Manual Sends and Send Requests__**\n\n"
                "-# - Discord User ID of the user submitting the send or request\n"
                "-# - Discord User ID of the Dom/me receiving the send\n"
                "-# - Amount submitted\n"
                "-# - Currency\n"
                "-# - Service or platform selected by the user\n"
                "-# - Optional note submitted with the request\n"
                "-# - Request status, including whether the request was accepted or denied\n"
                "-# - Denial reason, where provided\n\n"
                "**__Leaderboard and Statistics Features__**\n\n"
                "-# - Send totals\n"
                "-# - Send counts\n"
                "-# - Registered Dom/me and Sub associations\n"
                "-# - Leaderboard rank and related calculated statistics\n"
                "-# - Latest tracked send information where required to display user statistics\n\n"
                "**__Counting Feature__**\n\n"
                "-# - Discord server ID\n"
                "-# - Counting channel ID\n"
                "-# - Current count value\n"
                "-# - Discord User ID of the most recent valid counter\n"
                "-# - Count rescue status and related timestamps where the feature is active\n\n"
                "**__Reports__**\n\n"
                "-# - Discord User ID of the reporting user\n"
                "-# - Discord server ID\n"
                "-# - Report text submitted by the user\n"
                "-# - Optional screenshot or attachment, where provided\n"
                "-# - Submission timestamp"
            ),
        )
    )

    view.add_item(
        _privacy_container(
            title="## Purpose of Processing",
            body=(
                "Rob uses collected or received information only for the purpose of providing, maintaining, securing, and administering its configured features.\n\n"
                "This may include processing registrations, verifying access to role-restricted features, receiving Throne webhook events, posting send notifications, maintaining leaderboard totals, processing send requests, operating the counting feature, receiving issue reports, and preserving bot configuration across restarts.\n\n"
                "Rob may also process stored information to prevent duplicate tracking, diagnose failed bot actions, maintain appropriate records for accepted or denied send requests, and ensure users only access features they are permitted to use.\n\n"
                "Rob does not sell user information, use it for advertising, or use it to create user profiles outside the operation of Rob’s own features."
            ),
        )
    )

    view.add_item(
        _privacy_container(
            title="## Data Minimisation and Third-Party Services",
            body=(
                "Rob is intended to minimise the information it collects and stores.\n\n"
                "Where possible, Rob avoids storing information that is not required for its configured features. If a third-party service provides information that is not required, reasonable steps will be taken to ignore, minimise, or avoid retaining that information.\n\n"
                "Rob relies on third-party services, including Discord and Throne, to provide certain feature-related information. The information made available to Rob may change if those services update their systems, payloads, APIs, or integrations.\n\n"
                "If Rob receives information that is unexpected, unnecessary, or potentially sensitive, reasonable steps will be taken to review the issue, reduce unnecessary storage, and notify affected users where appropriate."
            ),
        )
    )

    view.add_item(
        _privacy_container(
            title="## Public Display of Information",
            body=(
                "Certain Rob features may display information in Discord channels configured by the server.\n\n"
                "This may include send tracker notifications, leaderboard entries, send request outcomes, counting messages, and other feature-related status messages.\n\n"
                "Visibility of this information depends on the server’s channel configuration, Discord permissions, and Rob’s configured feature channels.\n\n"
                "Users should avoid submitting sensitive personal information through Rob commands, reports, send notes, third-party gift messages, or other inputs unless that information is necessary for the relevant feature."
            ),
        )
    )

    view.add_item(
        _privacy_container(
            title="## User Control and Data Removal",
            body=(
                "Users may request removal of information associated with them in Rob.\n\n"
                "Where supported, users may run `/optout` to permanently remove information associated with their Discord account from Rob. This may remove registrations, tracked associations, statistics, and other feature-related records connected to that user.\n\n"
                "This action is irreversible.\n\n"
                "Some information may need to be retained where required for security, abuse prevention, technical integrity, or administrative recordkeeping. Where retention is necessary, Rob will aim to retain only the minimum information required.\n\n"
                "Questions or concerns regarding information collected, stored, or used by Rob should be directed to Pat."
            ),
        )
    )

    view.add_item(
        _privacy_container(
            title="## Changes to This Notice",
            body=(
                "This privacy notice may be updated if Rob’s features, integrations, data handling practices, or storage requirements change.\n\n"
                "Where a material change affects the information Rob collects, stores, or uses, reasonable steps should be taken to make the updated notice available to users.\n\n"
                "The effective date of this notice is shown below."
            ),
        )
    )

    return RenderedMessage(view=view)


def privacy_card() -> RenderedMessage:
    return privacy_notice_message()
